### ISSUE TITLE
[Mac] Display Above Full Screen Apps

### ISSUE THREAD

**Issue by tomershvueli** [virejdasani/Geniemoji#5]
Thanks for this project! It's a good combination of other solutions I've used that don't quite fit the use case I'm looking for. 

One thing I've noticed is that if I'm working in a full screen app, say Firefox, and hit 'Control + E', my focus gets taken to the Desktop space with Geniemoji opened up. Is there a way for Geniemoji to be a modal window on top of full screen apps?

**Comment by virejdasani** [comment]
I'll try to implement this in the next week. Btw, you are on MacOS, right?

**Comment by tomershvueli** [comment]
Correct!

**Comment by virejdasani** [comment]
I have implemented this in Geniemoji v4.0.0, you can download it from the website [here](https://virejdasani.github.io/Geniemoji/download.html) 👍

**Comment by tomershvueli** [comment]
Yep, can confirm this works great now!
