### ISSUE TITLE
Write Emoji Instead of Copying

### ISSUE THREAD

**Issue by tomershvueli** [virejdasani/Geniemoji#6]
Me again :)

I'm not sure if this is a limitation of Electron or cross-platform applications, but am thinking it could be handy if when selecting an emoji from the list it actually writes it out where the cursor is instead of copying the character. This saves a bit on the user, as well as not overwriting the user's clipboard which may contain data they planned on using. 

Are there any plans to implement something like this?

**Comment by virejdasani** [comment]
I'll try to implement this too, thanks!

**Comment by tomershvueli** [comment]
@virejdasani I did some looking into this. To send keyboard events the `sendInputEvent` method exists, however, I /believe/ this will only work to send keyboard events to our BrowserWindow, which isn't what we want in this case. What I am seeing though, is we could potentially [use RobotJS in order to send keyboard strokes to the OS](https://github.com/electron/electron/issues/8977#issuecomment-421283070). It's your call if you want to move forward with something like that. If so, I can put in a PR and bring it in along with this functionality.

**Comment by virejdasani** [comment]
Thanks a lot, ao ahead with making the PR and I'll merge it!

**Comment by tomershvueli** [comment]
@virejdasani see PR #7 - happy to answer any questions you may have!

**Comment by virejdasani** [comment]
Resolved in https://github.com/virejdasani/Geniemoji/pull/9
